tap "dprint/dprint"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
tap "mongodb/brew"
tap "octave-app/octave-app"
tap "schniz/tap"
brew "ansible"
brew "aria2"
brew "bat"
brew "bitwise"
brew "libpng"
brew "pkg-config"
brew "cairo"
brew "cassowary"
brew "cmake"
brew "cocoapods"
brew "composer"
brew "curl"
brew "deno"
brew "docker"
brew "docker-compose"
brew "dprint"
brew "exa"
brew "giflib"
brew "unbound"
brew "gobject-introspection"
brew "jpeg"
brew "ffmpeg"
brew "fish"
brew "fnm"
brew "git"
brew "qt@5"
brew "git-cola"
brew "git-gui"
brew "git-lfs"
brew "pinentry-mac"
brew "gnupg"
brew "go"
brew "htop"
brew "imagemagick"
brew "iperf"
brew "pango"
brew "librsvg"
brew "llvm"
brew "mas"
brew "mkcert"
brew "mosh"
brew "nano"
brew "neofetch"
brew "neovim"
brew "node"
brew "openblas"
brew "openjdk@11"
brew "php"
brew "pinentry-mac"
brew "qemu"
brew "podman"
brew "postgresql"
brew "qt"
brew "pyqt"
brew "rclone"
brew "ripgrep"
brew "rsync"
brew "rust"
brew "rust-analyzer"
brew "smartmontools"
brew "speedtest-cli"
brew "starship"
brew "tmux"
brew "unzip"
brew "watchman"
brew "websocat"
brew "wget"
brew "wrk", args: ["HEAD"]
brew "yarn"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
cask "1password"
cask "4k-video-downloader"
cask "adguard"
cask "adguard-vpn"
cask "altair-graphql-client"
cask "android-file-transfer"
cask "android-studio"
cask "app-cleaner"
cask "browserstacklocal"
#cask "coconutbattery"
cask "cyberduck"
cask "datagrip"
cask "figma"
cask "firefox"
cask "folx"
cask "font-fira-code"
cask "framer"
cask "google-chrome"
cask "iina"
cask "imazing"
#cask "krisp"
cask "macs-fan-control"
cask "macupdater"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "miniforge"
cask "miro"
cask "netnewswire"
cask "notion"
cask "numi"
cask "octave-app"
cask "paw"
cask "postman"
cask "raspberry-pi-imager"
#cask "silicon"
cask "slack"
#cask "sublime-text"
cask "telegram"
cask "utm"
cask "visual-studio-code"
#cask "webstorm"
mas "Apple Configurator 2", id: 1037126344
mas "Asphalt 8+", id: 1563005359
mas "Blackmagic RAW Speed Test", id: 1466185689
mas "Boop", id: 1518425043
mas "Cleaner for Xcode", id: 1296084683
mas "Data Modeler", id: 1575153701
mas "Developer", id: 640199958
mas "Disk Speed Test", id: 425264550
mas "iMovie", id: 408981434
mas "iPreview", id: 1519213509
mas "Medis", id: 1579200037
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Ora", id: 1340501510
mas "Sequel Ace", id: 1518036000
mas "The Unarchiver", id: 425424353
mas "Transporter", id: 1450874784
mas "Treenity", id: 1208520991
mas "WebSocket Client", id: 1399498094
mas "Xcode", id: 497799835
