tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "lapce/lapce"
tap "mongodb/brew"
#tap "mutagen-io/mutagen"
tap "ngrok/ngrok"
tap "oven-sh/bun"
tap "tantalor93/dnspyre"
tap "tursodatabase/tap"
tap "yt-dlp/taps"
brew "age"
brew "ansible"
brew "giflib"
brew "aria2"
brew "bash"
brew "bashdb"
brew "bat"
brew "bc"
brew "bfg"
brew "bind"
brew "bitwise"
brew "pkg-config"
brew "cairo"
brew "cassowary"
brew "certbot"
brew "cmake"
brew "cocoapods"
brew "composer"
brew "curl"
brew "deno"
#brew "docker"
#brew "docker-compose"
brew "dprint"
brew "exiftool"
brew "eza"
brew "fd"
brew "unbound"
brew "fdupes"
brew "ffmpeg"
brew "fish"
brew "fnm"
brew "fpart"
brew "git"
brew "git-cola"
brew "git-crypt"
brew "git-delta"
brew "git-filter-repo"
brew "git-lfs"
brew "git-remote-gcrypt"
brew "gnupg"
brew "glib"
brew "go"
brew "htop"
brew "imagemagick"
brew "iperf"
brew "iperf3"
brew "pango"
brew "jpeg"
brew "kind"
brew "less"
brew "libffi"
brew "librsvg"
brew "llvm"
brew "mas"
brew "mkcert"
brew "mosh"
brew "nano"
brew "neofetch"
brew "neovim"
brew "node"
brew "nss"
brew "octave"
brew "openblas"
brew "openjdk@11"
brew "php"
brew "pinentry-mac"
brew "pipx"
brew "pixman"
brew "pnpm"
brew "qemu"
brew "podman"
brew "postgresql@14"
brew "qt"
brew "pyqt"
brew "rclone"
brew "ripgrep"
brew "rsync"
brew "rust"
brew "rust-analyzer"
brew "shellcheck"
brew "smartmontools"
brew "speedtest-cli"
brew "starship"
brew "testdisk"
brew "tmux"
brew "tmuxinator"
brew "trash"
brew "tree"
brew "unzip"
brew "volta"
brew "wakeonlan"
brew "watchman"
brew "websocat"
brew "wget"
brew "wrk"
brew "yarn"
brew "zig"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
#brew "mutagen-io/mutagen/mutagen"
#brew "mutagen-io/mutagen/mutagen-compose"
brew "oven-sh/bun/bun"
brew "yt-dlp"
brew "tantalor93/dnspyre/dnspyre"
brew "tursodatabase/tap/turso"
cask "1password"
cask "adguard"
cask "adguard-vpn"
cask "adobe-acrobat-reader"
#cask "affinity-designer"
#cask "affinity-photo"
cask "aldente"
cask "alt-tab"
cask "altair-graphql-client"
cask "altserver"
cask "android-file-transfer"
cask "android-studio"
cask "appcleaner"
cask "arctype"
#cask "arq"
#cask "arq-cloud-backup"
#cask "avibrazil-rdm"
cask "balenaetcher"
cask "beekeeper-studio"
#cask "bettertouchtool"
cask "boop"
cask "browserstacklocal"
cask "coconutbattery"
cask "codeedit"
cask "cryptomator"
cask "cyberduck"
cask "datagrip"
cask "diffusionbee"
cask "docker"
#cask "fedora-media-writer"
cask "figma"
cask "firefox"
cask "fleet"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "framer"
#cask "eloston-chromium"
cask "fsnotes"
cask "iina"
cask "imazing"
cask "kap"
#cask "knockknock"
#cask "krisp"
cask "lapce"
#cask "logseq"
cask "macfuse"
cask "macs-fan-control"
cask "macupdater"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "miniforge"
cask "miro"
#cask "moonlight"
cask "multipass"
#cask "monitorcontrol"
#cask "mounty"
cask "netnewswire"
cask "ngrok"
cask "notion"
cask "numi"
#cask "outline-manager"
cask "obsidian"
cask "onlyoffice"
cask "paragon-ntfs"
cask "parsec"
cask "postgres-unofficial"
cask "postico"
cask "postman"
#cask "proxyman"
#cask "pycharm"
#cask "qbittorrent"
cask "raindropio"
cask "rapidapi"
#cask "raspberry-pi-imager"
cask "raycast"
cask "rectangle"
cask "redis-pro"
cask "redisinsight"
cask "rustrover"
#cask "sensei"
#cask "slack"
cask "soulver"
cask "spotify"
cask "sublime-text"
cask "tableplus"
#cask "teamviewer"
cask "tailscale"
#cask "taskexplorer"
cask "telegram-desktop"
cask "utm"
cask "veracrypt"
cask "virtualbox-beta"
cask "visual-studio-code"
cask "visual-studio-code-insiders"
cask "vmware-fusion"
cask "webstorm"
#cask "wifi-explorer-pro"
#cask "zerotier-one"
cask "vnc-viewer"
cask "webstorm"
#cask "zoom"
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "Apple Configurator", id: 1037126344
mas "Baking Soda", id: 1601151613
mas "Blackmagic RAW Speed Test", id: 1466185689
mas "CapCut", id: 1500855883
#mas "Cleaner for Xcode", id: 1296084683
#mas "Codye", id: 1516894961
mas "CodeOfWar", id: 1310262344
mas "CompareMerge2", id: 1459748650
mas "Core Tunnel", id: 1354318707
mas "Craft", id: 1487937127
mas "Data Modeler", id: 1575153701
#mas "Developer", id: 640199958
mas "DaVinci Resolve", id: 571213070
mas "Disk Decipher", id: 516538625
mas "Disk Speed Test", id: 425264550
mas "Hex Fiend", id: 1342896380
#mas "Home Design 3D", id: 1342163391
#mas "iMovie", id: 408981434
mas "Infuse", id: 1136220934
mas "iPreview", id: 1519213509
#mas "Live Home 3D", id: 1066144116
#mas "Medis 1", id: 1063631769
mas "Medis", id: 1579200037
mas "Microsoft Remote Desktop", id: 1295203466
#mas "Mockup", id: 1527554407
#mas "MQTT Explorer", id: 1455214828
#mas "Notability", id: 360593530
#mas "Octotree", id: 1457450145
#mas "Ora", id: 1340501510
#mas "Outline", id: 1356178125
mas "Noted", id: 1446580517
mas "Photomator", id: 1444636541
mas "Pixelmator Pro", id: 1289583905
#mas "Planner 5D", id: 1310584536
mas "RectLabel", id: 1490990105
mas "Save to Raindrop.io", id: 1549370672
#mas "Sculptor", id: 1493318997
mas "Sequel Ace", id: 1518036000
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
#mas "Transporter", id: 1450874784
mas "Vinegar", id: 1591303229
mas "VN", id: 1494451650
#mas "Wappalyzer", id: 1520333300
mas "WebSocket Client", id: 1399498094
mas "Xcode", id: 497799835
